name: trying using docker actiion

on:
  workflow_dispatch
jobs:
  job_1:
    runs-on: ubuntu-latest
    steps:
      - name: first step
        run: echo "This is the first step in the job runs on ubuntu not in docker container"

      - name: building docker image
        uses: docker://alpine:latest
        with: 
          args: echo "Hello from Docker action"
      
      - name: another step
        run: echo "This is another step in the job out docker container"

           
          
  
  
