name: trying built-in actions
on:
  workflow_dispatch
jobs:
  job_1:
    runs-on: ubuntu-latest
    step:
      - name: say Hello
        uses: Robs-Organisation/Robs-action@v1.7
        with: Devops_Team_4
          
  
  
