name: trying built-in actions

on:
  workflow_dispatch
jobs:
  job_1:
    runs-on: ubuntu-latest
    steps:
      - name: say Hello
        uses: Robs-Organisation/Robs-action@v1.7
        with: 
          team: DevopsTeam4
          
  
  
