on:
   workflow_dispatch:

jobs:
  job_1:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1
        run: echo "This is Job 1, Step 1"
        
  job_2:
    runs-on: ubuntu-latest
    needs: job_1
    steps:
      - name: Step 1
        run: echo "This is Job 2, Step 1, after Job 1 completion"   
  job_3:
    runs-on: ubuntu-latest
    needs: job_1
    steps:
      - name: Step 1
        run: echo "This is Job 3, Step 1, after Job 1 and Job 2 completion"
  job_4:
    runs-on: ubuntu-latest
    needs: job_3
    steps:
      - name: Step 1
        run: echo "This is Job 4, Step 1, after Job 3 completion"       
        
