name: set up first workflow

on:
  push: 
    branches:
      - main
      - master
      - dev

jobs:
  first-example:
    runs-on: ubuntu-latest
    steps:
      - name: print hello message
        run: echo "Hello World!"

      - name: checkout
        uses: actions/checkout@v6-beta

      - name: validate  
        run: ls -la
      
