name: trying using matrix strategy

on:
  workflow_dispatch:

jobs:
  job_1:
    strategy:
        fail-fast: false
        max-parallel: 3
        matrix:
            os: [ubuntu-latest, windows-latest, macos-latest]
            node_version: [14.x, 16.x, 18.x]
    runs-on: ${{ matrix.os }}
    steps:
        - name: step running on different OS
          run: echo "This job is running on ${{ matrix.os }}"  
          
        - name: setup node version
          uses: actions/setup-node@v3.6.0
          with:
            node-version: ${{ matrix.node_version }}   


